Fix TypeError
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'

't' was undefined here, corrected so that it is 'self.t' -- the
parameter -- as it should.