test(aliby): fix typo
WHY IS THIS CHANGE NEEDED?:
- https://git.ecdf.ed.ac.uk/swain-lab/aliby/aliby/-/jobs/56786 because
  AttributeError: 'function' object has no attribute 'shape'

REFERENCES:
- issue #53